# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Manesha\Documents\GitHub\AtlassTools\MainTool\MainTool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 901)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(440, 0, 881, 851))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_2 = QtWidgets.QTableView(self.tab)
        self.tableView_2.setGeometry(QtCore.QRect(10, 10, 651, 811))
        self.tableView_2.setObjectName("tableView_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 651, 811))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_2, "")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 0, 20, 851))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 831))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.projectNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.projectNameLabel.setFont(font)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.projectNameLabel)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.areaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.areaLabel.setFont(font)
        self.areaLabel.setObjectName("areaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.areaLabel)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.xminLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xminLabel.setFont(font)
        self.xminLabel.setIndent(20)
        self.xminLabel.setObjectName("xminLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.xminLabel)
        self.xminLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.xminLineEdit.setObjectName("xminLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.xminLineEdit)
        self.yminLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yminLabel.setFont(font)
        self.yminLabel.setIndent(20)
        self.yminLabel.setObjectName("yminLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.yminLabel)
        self.yminLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.yminLineEdit.setObjectName("yminLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.yminLineEdit)
        self.xmaxLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xmaxLabel.setFont(font)
        self.xmaxLabel.setIndent(20)
        self.xmaxLabel.setObjectName("xmaxLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.xmaxLabel)
        self.xmaxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.xmaxLineEdit.setObjectName("xmaxLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.xmaxLineEdit)
        self.ymaxLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ymaxLabel.setFont(font)
        self.ymaxLabel.setIndent(20)
        self.ymaxLabel.setObjectName("ymaxLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ymaxLabel)
        self.ymaxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ymaxLineEdit.setObjectName("ymaxLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ymaxLineEdit)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.captureDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.captureDateLabel.setFont(font)
        self.captureDateLabel.setObjectName("captureDateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.captureDateLabel)
        self.captureDateLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.captureDateLineEdit.setObjectName("captureDateLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.captureDateLineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1338, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionLoad_Project_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project_2.setObjectName("actionLoad_Project_2")
        self.actionProject_Meta_Data = QtWidgets.QAction(MainWindow)
        self.actionProject_Meta_Data.setObjectName("actionProject_Meta_Data")
        self.menuFile.addAction(self.actionLoad_Project)
        self.menuFile.addAction(self.actionLoad_Project_2)
        self.menuEdit.addAction(self.actionProject_Meta_Data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Process 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Process 2"))
        self.projectNameLabel.setText(_translate("MainWindow", "Project Name :"))
        self.areaLabel.setText(_translate("MainWindow", "Area"))
        self.label.setText(_translate("MainWindow", "Boundries"))
        self.xminLabel.setText(_translate("MainWindow", "Xmin"))
        self.yminLabel.setText(_translate("MainWindow", "Ymin"))
        self.xmaxLabel.setText(_translate("MainWindow", "Xmax"))
        self.ymaxLabel.setText(_translate("MainWindow", "Ymax"))
        self.pushButton.setText(_translate("MainWindow", "Load"))
        self.captureDateLabel.setText(_translate("MainWindow", "Capture Date"))
        self.menuFile.setTitle(_translate("MainWindow", "Project"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionLoad_Project.setText(_translate("MainWindow", "New Project"))
        self.actionLoad_Project_2.setText(_translate("MainWindow", "Load Project"))
        self.actionProject_Meta_Data.setText(_translate("MainWindow", "Project Meta Data"))

    def actionLoad_Project():
        print("Load file")
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

